export type OpportunityProfile = {
  targetRoles: string[];
  domains: string[];
  strongSkills: string[];
  supportingSkills: string[];
  preferredLocations: string[];
  paidSignals: string[];
  englishSignals: string[];
  avoid: string[];
};

export const saadOpportunityProfile: OpportunityProfile = {
  targetRoles: [
    "ai engineer",
    "ai researcher",
    "machine learning engineer",
    "ml engineer",
    "ml researcher",
    "computer vision engineer",
    "computer vision researcher",
    "vision researcher",
    "research engineer",
    "research scientist",
    "applied scientist",
    "applied researcher",
    "research fellow",
    "data scientist",
    "doctoral researcher",
    "doctoral candidate",
    "phd candidate",
    "phd student",
    "phd",
    "research assistant",
    "postdoc",
    "postdoctoral researcher",
    "nlp engineer",
    "nlp researcher",
    "scientific software engineer",
    "clinical ai researcher",
    "biomedical engineer",
  ],
  domains: [
    "medical imaging",
    "medical image analysis",
    "computer vision",
    "biomedical ai",
    "health ai",
    "digital health",
    "radiology",
    "mri",
    "ct imaging",
    "computed tomography",
    "segmentation",
    "image analysis",
    "deep learning",
    "llm",
    "rag",
    "semantic search",
  ],
  strongSkills: [
    "python",
    "pytorch",
    "tensorflow",
    "fastapi",
    "next.js",
    "react",
    "typescript",
    "machine learning",
    "deep learning",
    "mlops",
    "computer vision",
    "segmentation",
    "nifti",
    "dicom",
  ],
  supportingSkills: [
    "docker",
    "sql",
    "postgres",
    "neon",
    "api",
    "cloud",
    "data pipeline",
    "statistics",
    "visualization",
  ],
  preferredLocations: [
    "germany",
    "berlin",
    "munich",
    "erlangen",
    "netherlands",
    "switzerland",
    "austria",
    "denmark",
    "sweden",
    "finland",
    "norway",
    "belgium",
    "france",
    "ireland",
    "united kingdom",
    "uk",
    "europe",
    "remote",
  ],
  paidSignals: [
    "salary",
    "paid",
    "funded",
    "fully funded",
    "stipend",
    "employment contract",
    "remuneration",
    "gross per month",
    "gross salary",
    "tv-l",
    "tvöd",
    "collective agreement",
    "doctoral researcher",
    "research assistant",
  ],
  englishSignals: [
    "english",
    "fluent english",
    "working language is english",
    "excellent english",
    "international team",
    "english-speaking",
  ],
  avoid: [
    "german required",
    "fluent german",
    "native german",
    "deutsch erforderlich",
    "verhandlungssicheres deutsch",
    "sales",
    "business development",
    "frontend only",
    "web3",
    "crypto",
    "blockchain",
    "principal engineer",
    "staff engineer",
    "10+ years",
    "8+ years",
    "unpaid",
    "volunteer",
    "data analyst",
    "business analyst",
    "business intelligence",
    "bi analyst",
    "marketing manager",
    "account executive",
    "account manager",
    "talent acquisition",
    "recruiter",
    "financial analyst",
    "data entry",
    "regulatory affairs",
    "clinical trial",
    "game developer",
    "ios developer",
    "android developer",
    "product manager",
    "project manager",
    "scrum master",
    "no coding",
    "non-technical",
  ],
};
